### ISSUE TITLE
Caching Tiling properties

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#130]
We should review the properties of the Tiling class and decide which to properly cache.

**Comment by jaypantone** [comment]
```
    @property
    def dimensions(self) -> Tuple[int, int]:
        if not hasattr(self, "_dimensions"):
            obcells = union_reduce(ob.pos for ob in self._obstructions)
            reqcells = union_reduce(
                union_reduce(req.pos for req in reqlist)
                for reqlist in self._requirements
            )
            all_cells = obcells | reqcells
            rows = set(x for (x, y) in all_cells)
            cols = set(y for (x, y) in all_cells)
            if not rows and not cols:
                self._dimensions = (1, 1)
            else:
                self._dimensions = (max(rows) + 1, max(cols) + 1)
        return self._dimensions
```
duplicates a lot of `active_cells` code. Should just use 
`all_cells = self.active_cells`
as long as it's cached.

**Comment by christianbean** [comment]
Other suggestions:
- to_bytes
- symmetries (maybe with a dimensions flag?)

**Comment by jaypantone** [comment]
@christianbean I forgot to do anything with to_bytes. Should I? Why is it worth caching?

If we ever decide to cache GriddedPerms, then obviously it makes sense to cache to_bytes there, and symmetries.

**Comment by christianbean** [comment]
I agree, these suggestions make more sense on GriddedPerm
