### ISSUE TITLE
Pylint issue on tilings

### ISSUE THREAD

**Issue by enadeau** [PermutaTriangle/Tilings#144]
I think it's time to turn back on some of the pylint check on the tiling file

**Comment by jaypantone** [comment]
After the tiling-caching PR is approved, the following pylint ignores are all present and necessary to pass tests:
```
# pylint: disable=too-many-locals
# pylint: disable=too-many-lines
# pylint: disable=too-many-branches
# pylint: disable=arguments-differ
# pylint: disable=too-many-statements
# pylint: disable=import-outside-toplevel
```

**Comment by christianbean** [comment]
Some, e.g. `pylint: disable=import-outside-toplevel` should be made local to the issue in get genf
