### ISSUE TITLE
insertion_point_placements(2) does not work / is not implemented

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#241]
I think this is because it has the strategy
```python
strat.CellInsertionFactory(
    maxreqlen=length, ignore_parent=True, one_cell_only=False
),
```
which has the lines
```python
if self.one_cell_only:
   assert self.maxreqlen == 1 and self.ignore_parent
```

Not sure what our goal is here.

**Comment by christianbean** [comment]
The purpose is that we only use it when inserting single points, in the attempt to get a tiling with all cells positive. Consider what you are asking for with inserting 12 and 21. It will keep inserting until it can no longer insert any other length 2 gridded perm into a cell. Thats a lot of work, and I don't think it is what you want. I could and probably should have edited the pack to not accept a length argument.

Perhaps you want to edit this pack to have a RequirementInsertionFactory as an expansion strategy with the maxreqlen?

**Comment by jaypantone** [comment]
I'll leave the pack curation up to the rest of you, since I don't have a very good sense of how all the strategies interact. Whatever we do, we just shouldn't have a parameter that bugs when it's used.
