### ISSUE TITLE
Tilings with > max_assumptions are still stored in the classdb

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/Tilings#477]
They are sent to the classdb to get a label, but then the rule is not added. This is a waste of memory.

**Comment by christianbean** [comment]
One solution is to have `LimitedAssumptionTileScope ` override the method `CombinatorialSpecificationSearcher._rules_from_strategy` rather than `CombinatorialSpecificationSearcher._expand`.

Something like:
```py
for rule in super()._rules_from_strategy(comb_class, strategy):
    if "GOOD":
        yield rule
```
