### ISSUE TITLE
Drop tilings dependecy on pymongo

### ISSUE THREAD

**Issue by enadeau** [PermutaTriangle/Tilings#60]
Use the future database api to get information for database verification

**Comment by christianbean** [comment]
This only appears in the setup.py file on develop now, however the future database has not been properly implemented yet.

**Comment by enadeau** [comment]
The new database for 1x1 tilings will get the information from our api using request so pymongo won't be needed.

What about the `dbconf.py` can we also remove it?

**Comment by christianbean** [comment]
It was quietly removed with PR #115
